from typing import Protocol
from cctv_monitor.models.device import DeviceConfig, DeviceInfo
from cctv_monitor.models.status import CameraChannelStatus, DiskHealthStatus, ChannelRecordingStatus
from cctv_monitor.models.snapshot import SnapshotResult
from cctv_monitor.models.device_health import DeviceHealthSummary
from cctv_monitor.models.capabilities import DeviceCapabilities
from cctv_monitor.core.types import ChannelId


class DeviceDriver(Protocol):
    async def connect(self, config: DeviceConfig) -> None: ...
    async def disconnect(self) -> None: ...
    async def get_device_info(self) -> DeviceInfo: ...
    async def get_camera_statuses(self) -> list[CameraChannelStatus]: ...
    async def get_disk_statuses(self) -> list[DiskHealthStatus]: ...
    async def get_recording_statuses(self) -> list[ChannelRecordingStatus]: ...
    async def get_snapshot(self, channel_id: ChannelId) -> SnapshotResult: ...
    async def check_health(self) -> DeviceHealthSummary: ...
    async def detect_capabilities(self) -> DeviceCapabilities: ...
